title: Byt3r Blog
description: Just a byt3r with a tech blog.
baseurl: ""
url: "https://byt3rr.github.io" 
twitter_username: byt3rr
github_username:  byt3rr

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
